import YAML from "yaml";
import { Subscription } from "./types";

export function generateVisualYaml(sub: Subscription): string {
  if (!sub.visualConfig) return sub.yamlConfig || "";

  const { baseConfig, proxyProviders, chainProxies, rules } = sub.visualConfig;

  let finalDoc: any = {};
  
  // 1. Parse base config
  if (baseConfig) {
    try {
      finalDoc = YAML.parse(baseConfig) || {};
    } catch (e) {
      console.error("Error parsing base config", e);
    }
  }

  if (!finalDoc.proxies) finalDoc.proxies = [];
  if (!finalDoc["proxy-groups"]) finalDoc["proxy-groups"] = [];
  if (!finalDoc.rules) finalDoc.rules = [];

  const allNodeNames: string[] = [];

  // 2. Add Proxy Providers
  if (proxyProviders) {
    for (const provider of proxyProviders) {
      if (provider.type === "content" && provider.content) {
        try {
          const nodes = YAML.parse(provider.content);
          if (Array.isArray(nodes)) {
            nodes.forEach(node => {
              if (node.name) {
                finalDoc.proxies.push(node);
                allNodeNames.push(node.name);
              }
            });
          }
        } catch (e) {
          console.error(`Error parsing content for provider ${provider.name}`, e);
        }
      } else if (provider.type === "url" && provider.fetchedNodes) {
        provider.fetchedNodes.forEach(node => {
          if (node.name) {
            finalDoc.proxies.push(node);
            allNodeNames.push(node.name);
          }
        });
      }
    }
  }

  // 3. Add Chain Proxies (Relay)
  const AUTO_SELECT_GROUP_NAME = "🚀 自动优选加速";
  
  // We only add the auto-select group if we have chain proxies or if there are nodes.
  // Actually, user wants it to be added by default to use as first hop.
  if (allNodeNames.length > 0) {
    const existingAutoSelect = finalDoc["proxy-groups"].find((g: any) => g.name === AUTO_SELECT_GROUP_NAME);
    if (!existingAutoSelect) {
      finalDoc["proxy-groups"].push({
        name: AUTO_SELECT_GROUP_NAME,
        type: "url-test",
        proxies: [...allNodeNames],
        url: "http://www.gstatic.com/generate_204",
        interval: 300,
        tolerance: 50
      });
    } else {
      existingAutoSelect.proxies = [...new Set([...(existingAutoSelect.proxies || []), ...allNodeNames])];
    }
  }

  if (chainProxies) {
    for (const chain of chainProxies) {
      if (chain.secondHopConfig) {
        try {
          const secondHopNode = YAML.parse(chain.secondHopConfig);
          
          if (secondHopNode && secondHopNode.name) {
            // Check if it's socks5 and uses user/password instead of username/password
            if (secondHopNode.type === 'socks5') {
              if (secondHopNode.user && !secondHopNode.username) {
                secondHopNode.username = secondHopNode.user;
                delete secondHopNode.user;
              }
            }

            // Use dialer-proxy instead of relay group for Meta/Mihomo core
            secondHopNode["dialer-proxy"] = AUTO_SELECT_GROUP_NAME;
            finalDoc.proxies.push(secondHopNode);
            
            // Add a select group so rules can reference the chain proxy by the given name
            finalDoc["proxy-groups"].push({
              name: chain.name,
              type: "select",
              proxies: [secondHopNode.name]
            });
          }
        } catch (e) {
          console.error(`Error parsing second hop config for ${chain.name}`, e);
        }
      }
    }
  }

  // Filter out invalid rules if any
  if (finalDoc.rules && Array.isArray(finalDoc.rules)) {
    finalDoc.rules = finalDoc.rules.filter((r: any) => typeof r === 'string' && r.length > 5);
  }

  // 5. Serialize to YAML
  let yamlString = YAML.stringify(finalDoc);

  // 6. Append Custom Rules as Raw String to preserve comments and order
  if (rules) {
    // Remove the empty rules array generated by stringify if it was empty
    yamlString = yamlString.replace(/rules:\s*\[\]\n?/g, '');
    
    // Add rules header and the raw rules content
    if (!yamlString.includes('rules:')) {
      yamlString += '\nrules:\n';
    }
    
    // Ensure each line that is not a comment starts with proper indentation if needed, 
    // or just append it since rules are usually just strings.
    // The safest way is to just append the user's raw input block directly under rules:
    yamlString += rules.split('\n').map(line => {
      if (line.trim().startsWith('- ') || line.trim().startsWith('#') || line.trim() === '') {
        return `  ${line}`;
      }
      return `  - ${line}`; // auto fix missing dash
    }).join('\n');
    yamlString += '\n';
  }

  return yamlString;
}
